fix boot script for RELEASE_CONFIG_FILE configuration

diff --git a/priv/rel/files/boot b/priv/rel/files/boot
--- a/priv/rel/files/boot
+++ b/priv/rel/files/boot
@@ -90,17 +90,19 @@ relx_start_command() {
 # Convert .conf to sys.config using conform escript
 generate_config() {
     __schema_file="$REL_DIR/$REL_NAME.schema.exs"
-    if [ -z "$RELEASE_CONFIG_FILE" ]; then
-        __conform_file="$RELEASE_CONFIG_DIR/$REL_NAME.conf"
-    else
-        if [ -r "$RELEASE_CONFIG_FILE" ]; then
-            __conform_file="$RELEASE_CONFIG_FILE"
-        else
-            echo "$RELEASE_CONFIG_FILE not found"
-            exit 1
-        fi
-    fi
     if [ -f "$__schema_file" ]; then
+        __running_conf="$GENERATED_CONFIG_DIR/$REL_NAME.conf"
+        if [ -z "$RELEASE_CONFIG_FILE" ]; then
+            __conform_file="$RELEASE_CONFIG_DIR/$REL_NAME.conf"
+        else
+            if [ -r "$RELEASE_CONFIG_FILE" ]; then
+                cp "$__conform_file" "$__running_conf"
+                __conform_file="$RELEASE_CONFIG_FILE"
+            else
+                echo "$RELEASE_CONFIG_FILE not found"
+                exit 1
+            fi
+        fi
         if [ -f "$__conform_file" ]; then
             __running_conf="$GENERATED_CONFIG_DIR/$REL_NAME.conf"
             if [ ! -f "$__running_conf" ]; then
